# See https://pre-commit.com/#new-hooks for more information on this file.
# It allows to use semgrep itself inside pre-commit

- id: semgrep-docker-develop
  name: semgrep
  description: This hook runs semgrep:develop
  # See https://pre-commit.com/#docker_image for more information
  language: docker_image
  entry: returntocorp/semgrep:develop

- id: semgrep-docker
  name: semgrep
  description: This hook runs semgrep
  language: docker_image
  entry: returntocorp/semgrep:latest

- id: semgrep
  name: semgrep
  entry: semgrep
  language: python
  args: ["--disable-version-check", "--quiet", "--skip-unknown-extensions"]
