#! /bin/sh
#
# Fetch rules and targets prior for a more thorough rule-time benchmark.
#
# rule_dir: input/rules/???
# target_dir: input/grpc-docker-library/???
#
# Uses sh because bash is not installed within the semgrep docker container.
#
set -eu

mkdir -p input

cp ../r2c-rules/docker.yml input
cd input

# Obtain a shallow clone of a git repo for a specific commit
shallow_clone() {
  if [ -d "$name" ]; then
    echo "Reusing repo '$name'"
  else
    echo "Obtaining a shallow clone of git repo '$name', commit $commit"
    mkdir -p "$name"
    (
      cd "$name"
      git init
      git remote add origin "$url"
      git fetch --depth 1 origin "$commit"
      git checkout FETCH_HEAD -b tmp
    )
  fi
}

# Obtain semgrep rules and targets
name="grpc-docker-library"
url="https://github.com/grpc/grpc-docker-library.git"
commit="2ef4dc22614a5e82fad25ae33e5a8520773eca10"
shallow_clone
