(*
   Utilities for working with AST_generic.raw_tree
*)

type t = AST_generic.raw_tree

(*
   Return the first and the last token of the tree, if any.

   Note that it might be more efficient if the raw tree stored this
   location at each node but this would require changing the OCaml
   types generated by ocaml-tree-sitter (CST.ml files).
*)
val loc : t -> (AST_generic.tok * AST_generic.tok) option

(* Same as loc but return fake tokens in case the tree is empty *)
val unsafe_loc : t -> AST_generic.tok * AST_generic.tok

(* Extract all the Any nodes, in left-to-right order.
   (without descending recursively into these nodes)
*)
val anys : t -> AST_generic.any list
