#! /usr/bin/env bash
#
# Install python3 base on alpine.
#
# Taken from https://hub.docker.com/r/frolvlad/alpine-python3/dockerfile
#
set -eu

# This hack is widely applied to avoid python printing issues in docker
# containers.
# See: https://github.com/Docker-Hub-frolvlad/docker-alpine-python3/pull/13
export PYTHONUNBUFFERED=1

echo "Install Python3"

apk add --no-cache python3
if [[ ! -e /usr/bin/python ]]; then
  ln -sf python3 /usr/bin/python
fi

echo "Install pip"

python3 -m ensurepip
rm -r /usr/lib/python*/ensurepip
pip3 install --no-cache --upgrade pip setuptools wheel
if [[ ! -e /usr/bin/pip ]]; then
  ln -s pip3 /usr/bin/pip
fi
