#
# Copyright (c) 2026 Semgrep Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the file
# LICENSE for more details.
#
"""Tests for the rules_jvm_external maven_install.json parser.

Fixtures use the actual on-disk shapes produced by rules_jvm_external, as
documented in
https://github.com/bazel-contrib/rules_jvm_external/blob/master/private/rules/v1_lock_file.bzl
and verified against samples in
https://github.com/bazel-contrib/rules_jvm_external/tree/master/tests/custom_maven_install
(commit fetched 2026-09-04 at bazel-contrib/rules_jvm_external master).
"""
import json
from pathlib import Path

import pytest

from semdep.parsers.maven_install import _split_gav_coord
from semdep.parsers.maven_install import parse_maven_install
from semgrep.semgrep_interfaces.semgrep_output_v1 import Direct
from semgrep.semgrep_interfaces.semgrep_output_v1 import Maven
from semgrep.semgrep_interfaces.semgrep_output_v1 import Transitive
from semgrep.semgrep_interfaces.semgrep_output_v1 import Unknown


def _write_lockfile(tmp_path: Path, contents: dict) -> Path:
    lockfile = tmp_path / "maven_install.json"
    lockfile.write_text(json.dumps(contents, indent=2))
    return lockfile


# ---------------------------------------------------------------------------
# Coordinate splitter (legacy 0.1.0 `coord` shape only)
# ---------------------------------------------------------------------------


@pytest.mark.quick
@pytest.mark.parametrize(
    ["coord", "expected"],
    [
        # Standard three-part
        ("com.google.guava:guava:32.0.1-jre", ("com.google.guava:guava", "32.0.1-jre")),
        # Four-part with packaging
        ("org.slf4j:slf4j-api:jar:2.0.9", ("org.slf4j:slf4j-api", "2.0.9")),
        # Five-part with packaging + classifier
        (
            "com.google.inject:guice:jar:no_aop:5.1.0",
            ("com.google.inject:guice", "5.1.0"),
        ),
        # Malformed
        ("garbage", None),
        ("group:artifact", None),
        ("", None),
        # Missing group, artifact, or version
        (":artifact:1.0", None),
        ("group::1.0", None),
        ("group:artifact:", None),
    ],
)
def test_split_gav_coord(coord, expected):
    assert _split_gav_coord(coord) == expected


# ---------------------------------------------------------------------------
# Version 3 (current) — flat top-level `artifacts` MAP
# ---------------------------------------------------------------------------

V3_SAMPLE = {
    "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",
    "__INPUT_ARTIFACTS_HASH": {
        # Workspace declared only log4j-core as its direct dep. log4j-api is
        # transitive (pulled in by log4j-core).
        "org.apache.logging.log4j:log4j-core": -1659386931,
        "repositories": -1949687017,
    },
    "__RESOLVED_ARTIFACTS_HASH": {
        "org.apache.logging.log4j:log4j-api": 111,
        "org.apache.logging.log4j:log4j-core": 222,
    },
    "artifacts": {
        "org.apache.logging.log4j:log4j-api": {
            "shasums": {
                "jar": "0818930dc8d7e5e26abda60cccf03302e5d47a5e3e0c25a86a4b7dbfaadddddd"
            },
            "version": "2.14.0",
        },
        "org.apache.logging.log4j:log4j-core": {
            "shasums": {
                "jar": "4bf0e2c5af8e4525dfd0e58ef0c3b3fdd82f4b4fa9b3f6ce2a3f7c8e7dfeaaaa"
            },
            "version": "2.14.0",
        },
    },
    "dependencies": {
        "org.apache.logging.log4j:log4j-core": [
            "org.apache.logging.log4j:log4j-api",
        ],
    },
    "packages": {},
    "repositories": {
        "https://repo1.maven.org/maven2/": [
            "org.apache.logging.log4j:log4j-api",
            "org.apache.logging.log4j:log4j-core",
        ],
    },
    "services": {},
    "version": "3",
}


@pytest.mark.quick
def test_parse_v3_direct_and_transitive(tmp_path: Path):
    """v3 flat: __INPUT_ARTIFACTS_HASH keys (excluding 'repositories') are the
    workspace-declared direct roots. Everything else is transitive."""
    lockfile = _write_lockfile(tmp_path, V3_SAMPLE)

    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 2
    by_pkg = {d.package: d for d in deps}

    core = by_pkg["org.apache.logging.log4j:log4j-core"]
    assert core.version == "2.14.0"
    assert isinstance(core.ecosystem.value, Maven)
    assert isinstance(core.transitivity.value, Direct)
    assert core.allowed_hashes == {
        "sha256": ["4bf0e2c5af8e4525dfd0e58ef0c3b3fdd82f4b4fa9b3f6ce2a3f7c8e7dfeaaaa"]
    }

    api = by_pkg["org.apache.logging.log4j:log4j-api"]
    assert api.version == "2.14.0"
    assert isinstance(api.transitivity.value, Transitive)


@pytest.mark.quick
def test_parse_v3_without_input_hash_emits_unknown(tmp_path: Path):
    """When `__INPUT_ARTIFACTS_HASH` is missing, we cannot know which artifacts
    are direct roots. Emit Unknown rather than falsely marking everything
    Transitive (which is what the pre-fix parser did)."""
    sample = {
        "artifacts": {
            "org.slf4j:slf4j-api": {"shasums": {"jar": "aa"}, "version": "2.0.9"},
        },
        "dependencies": {},
        "packages": {},
        "repositories": {},
        "version": "3",
    }
    lockfile = _write_lockfile(tmp_path, sample)

    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 1
    assert isinstance(deps[0].transitivity.value, Unknown)


@pytest.mark.quick
def test_parse_v3_repositories_key_not_treated_as_direct(tmp_path: Path):
    """The reserved 'repositories' entry in __INPUT_ARTIFACTS_HASH is a bookkeeping
    signal, not an artifact — must be filtered out of direct roots."""
    sample = dict(V3_SAMPLE)
    sample["__INPUT_ARTIFACTS_HASH"] = {"repositories": 1}
    lockfile = _write_lockfile(tmp_path, sample)

    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    # With no artifact-keyed roots, both deps are transitive (not Unknown —
    # __INPUT_ARTIFACTS_HASH exists, just names no artifacts).
    for d in deps:
        assert isinstance(d.transitivity.value, Transitive)


@pytest.mark.quick
def test_parse_v3_aar_key_normalized_and_matches_direct_root(tmp_path: Path):
    """Real Android v3 lockfiles key `artifacts` as `group:artifact:aar` while
    `__INPUT_ARTIFACTS_HASH` uses the 2-part `group:artifact` shape. Emitted
    package must be the 2-part form so Maven advisories match, and the
    direct-root lookup must use the normalized key too."""
    sample = {
        "__INPUT_ARTIFACTS_HASH": {
            # Workspace declares androidx.core:core (no packaging suffix).
            "androidx.core:core": 42,
            "repositories": 1,
        },
        "artifacts": {
            # The artifacts map keys the same dep with the aar packaging suffix.
            "androidx.core:core:aar": {
                "shasums": {"jar": "aabb"},
                "version": "1.13.0",
            },
            # Plain 2-part key still works for non-Android artifacts.
            "com.google.guava:guava": {
                "shasums": {"jar": "ccdd"},
                "version": "32.0.1-jre",
            },
        },
        "dependencies": {},
        "version": "3",
    }
    lockfile = _write_lockfile(tmp_path, sample)

    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    by_pkg = {d.package: d for d in deps}

    # Note: package name is the 2-part form, not "androidx.core:core:aar".
    core = by_pkg["androidx.core:core"]
    assert core.version == "1.13.0"
    assert isinstance(core.transitivity.value, Direct)

    guava = by_pkg["com.google.guava:guava"]
    assert isinstance(guava.transitivity.value, Transitive)


@pytest.mark.quick
def test_parse_v3_prefers_jar_shasum_over_other_classifiers(tmp_path: Path):
    """When `shasums` has multiple classifier entries (e.g. `{jar, test-fixtures}`)
    the primary `jar` checksum must be selected explicitly, not by iteration order."""
    sample = {
        "__INPUT_ARTIFACTS_HASH": {
            "com.squareup.misk:misk-feature": 1,
            "repositories": 2,
        },
        "artifacts": {
            "com.squareup.misk:misk-feature": {
                "shasums": {
                    "test-fixtures": "tftftftf",
                    "jar": "jarjarjar",
                },
                "version": "0.30.0",
            },
        },
        "dependencies": {},
        "version": "3",
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert deps[0].allowed_hashes == {"sha256": ["jarjarjar"]}


@pytest.mark.quick
def test_parse_v3_shasum_falls_back_when_jar_missing(tmp_path: Path):
    """If `shasums` has no `jar` entry, fall back to whatever classifier is available."""
    sample = {
        "__INPUT_ARTIFACTS_HASH": {"some.group:only-aar": 1, "repositories": 2},
        "artifacts": {
            "some.group:only-aar:aar": {
                "shasums": {"aar": "aaronly"},
                "version": "1.0.0",
            },
        },
        "dependencies": {},
        "version": "3",
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert deps[0].allowed_hashes == {"sha256": ["aaronly"]}


@pytest.mark.quick
def test_parse_v3_missing_shasums_skips_hash(tmp_path: Path):
    """An artifact without a `shasums` field still emits with no allowed_hashes."""
    sample = {
        "__INPUT_ARTIFACTS_HASH": {"org.slf4j:slf4j-api": 1, "repositories": 2},
        "artifacts": {
            "org.slf4j:slf4j-api": {"version": "2.0.9"},
        },
        "dependencies": {"org.slf4j:slf4j-api": []},
        "version": "3",
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 1
    assert deps[0].allowed_hashes == {}
    assert isinstance(deps[0].transitivity.value, Direct)


# ---------------------------------------------------------------------------
# Legacy 0.1.0 — nested `dependency_tree.dependencies` LIST
# ---------------------------------------------------------------------------

V01_SAMPLE = {
    "dependency_tree": {
        "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",
        "__INPUT_ARTIFACTS_HASH": {
            # log4j-core was the sole workspace-declared root.
            "org.apache.logging.log4j:log4j-core": 111,
            "repositories": 222,
        },
        "__RESOLVED_ARTIFACTS_HASH": {},
        "conflict_resolution": {},
        "version": "0.1.0",
        "dependencies": [
            {
                "coord": "org.apache.logging.log4j:log4j-core:2.14.0",
                "dependencies": ["org.apache.logging.log4j:log4j-api"],
                "directDependencies": ["org.apache.logging.log4j:log4j-api"],
                "file": "v1/https/repo1.maven.org/maven2/.../log4j-core-2.14.0.jar",
                "mirror_urls": [
                    "https://repo1.maven.org/maven2/.../log4j-core-2.14.0.jar",
                ],
                "packages": ["org.apache.logging.log4j.core"],
                "sha256": "4bf0e2c5af8e4525dfd0e58ef0c3b3fdd82f4b4fa9b3f6ce2a3f7c8e7dfeaaaa",
                "url": "https://repo1.maven.org/maven2/.../log4j-core-2.14.0.jar",
            },
            {
                "coord": "org.apache.logging.log4j:log4j-api:2.14.0",
                "dependencies": [],
                "directDependencies": [],
                "file": "v1/https/repo1.maven.org/maven2/.../log4j-api-2.14.0.jar",
                "mirror_urls": [
                    "https://repo1.maven.org/maven2/.../log4j-api-2.14.0.jar",
                ],
                "packages": ["org.apache.logging.log4j"],
                "sha256": "0818930dc8d7e5e26abda60cccf03302e5d47a5e3e0c25a86a4b7dbfaadddddd",
                "url": "https://repo1.maven.org/maven2/.../log4j-api-2.14.0.jar",
            },
        ],
    }
}


@pytest.mark.quick
def test_parse_v01_direct_and_transitive(tmp_path: Path):
    """Legacy 0.1.0: coord is `group:artifact:version`. Direct roots come from
    the nested `dependency_tree.__INPUT_ARTIFACTS_HASH`."""
    lockfile = _write_lockfile(tmp_path, V01_SAMPLE)

    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 2
    by_pkg = {d.package: d for d in deps}

    core = by_pkg["org.apache.logging.log4j:log4j-core"]
    assert core.version == "2.14.0"
    assert isinstance(core.transitivity.value, Direct)
    assert core.allowed_hashes == {
        "sha256": ["4bf0e2c5af8e4525dfd0e58ef0c3b3fdd82f4b4fa9b3f6ce2a3f7c8e7dfeaaaa"]
    }

    api = by_pkg["org.apache.logging.log4j:log4j-api"]
    assert isinstance(api.transitivity.value, Transitive)


@pytest.mark.quick
def test_parse_v01_without_input_hash_emits_unknown(tmp_path: Path):
    """Legacy 0.1.0 with no __INPUT_ARTIFACTS_HASH → Unknown transitivity."""
    sample = {
        "dependency_tree": {
            "version": "0.1.0",
            "dependencies": [
                {"coord": "org.slf4j:slf4j-api:2.0.9", "sha256": "aa"},
            ],
        }
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 1
    assert isinstance(deps[0].transitivity.value, Unknown)


@pytest.mark.quick
def test_parse_v01_coordinate_variants(tmp_path: Path):
    """Legacy coords may carry packaging/classifier; both drop out."""
    sample = {
        "dependency_tree": {
            "version": "0.1.0",
            "__INPUT_ARTIFACTS_HASH": {"repositories": 1},
            "dependencies": [
                {"coord": "org.slf4j:slf4j-api:jar:2.0.9"},
                {"coord": "com.google.inject:guice:jar:no_aop:5.1.0"},
            ],
        }
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert {(d.package, d.version) for d in deps} == {
        ("org.slf4j:slf4j-api", "2.0.9"),
        ("com.google.inject:guice", "5.1.0"),
    }


@pytest.mark.quick
def test_parse_v01_skips_missing_coord(tmp_path: Path):
    """Entries without a `coord` field are skipped, not fatal."""
    sample = {
        "dependency_tree": {
            "version": "0.1.0",
            "dependencies": [
                {"coord": "org.slf4j:slf4j-api:2.0.9"},
                {"sha256": "no-coord-here"},
            ],
        }
    }
    lockfile = _write_lockfile(tmp_path, sample)
    deps, errors = parse_maven_install(lockfile, None)
    assert errors == []
    assert len(deps) == 1
    assert deps[0].package == "org.slf4j:slf4j-api"


# ---------------------------------------------------------------------------
# Format detection and defensive fallbacks
# ---------------------------------------------------------------------------


@pytest.mark.quick
def test_parse_empty_v01_dependencies(tmp_path: Path):
    """An empty 0.1.0 `dependencies` list returns no deps and no errors."""
    lockfile = _write_lockfile(
        tmp_path,
        {"dependency_tree": {"version": "0.1.0", "dependencies": []}},
    )
    deps, errors = parse_maven_install(lockfile, None)
    assert deps == []
    assert errors == []


@pytest.mark.quick
def test_parse_empty_v3_artifacts(tmp_path: Path):
    """An empty v3 `artifacts` map returns no deps and no errors."""
    lockfile = _write_lockfile(
        tmp_path,
        {"artifacts": {}, "dependencies": {}, "version": "3"},
    )
    deps, errors = parse_maven_install(lockfile, None)
    assert deps == []
    assert errors == []


@pytest.mark.quick
def test_parse_unrecognized_shape_returns_empty(tmp_path: Path):
    """A JSON blob that is neither shape does not raise; it returns empty so
    the pipeline continues."""
    lockfile = _write_lockfile(tmp_path, {"unrelated": "content"})
    deps, errors = parse_maven_install(lockfile, None)
    assert deps == []
    assert errors == []


@pytest.mark.quick
@pytest.mark.parametrize(
    "content",
    [
        "[]",  # top-level array
        '"just a string"',  # top-level string
        "42",  # top-level number
        "true",  # top-level bool
        "null",  # top-level null
    ],
)
def test_parse_non_object_root_does_not_crash(tmp_path: Path, content: str):
    """A valid JSON document whose root is not an object (array, scalar, null)
    must be handled like any other unrecognized shape rather than letting
    `.as_dict()` propagate into the caller."""
    lockfile = tmp_path / "maven_install.json"
    lockfile.write_text(content)

    deps, errors = parse_maven_install(lockfile, None)
    assert deps == []
    assert errors == []
