#
# Copyright (c) 2026 Semgrep Inc.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the file
# LICENSE for more details.
#
"""Regression tests for replacing generated parser artifacts."""
from __future__ import annotations

import runpy
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).resolve().parent


@pytest.mark.parametrize("removed", ["file", "manifest", "version_header", "parser"])
def test_regeneration_removes_obsolete_artifacts(tmp_path, removed):
    copy_generated = runpy.run_path(str(SCRIPTS_DIR / "regen-grammar"))[
        "copy_generated"
    ]
    langdir = tmp_path / "lang/toy"
    langdir.mkdir(parents=True)
    src = langdir / "ocaml-src"
    dst = tmp_path / "destination"
    for name in ("lib", "bin", "config"):
        (src / name).mkdir(parents=True)
    (src / ".gitignore").write_text("ignored\n")
    (src / "config/current").write_text("first\n")
    (src / "config/obsolete").write_text("obsolete\n")
    parser = src / "lib/parser.c"
    parser.write_text("// semgrep: generated by tree-sitter 0.26.3\n")
    manifest = langdir / "fyi.list"
    manifest.write_text("toy/current.js\ntoy/obsolete.js\n")
    (langdir / "current.js").write_text("current\n")
    (langdir / "obsolete.js").write_text("obsolete\n")

    copy_generated(src, dst, langdir)
    assert (dst / "config/obsolete").exists()
    assert (dst / "fyi/toy/obsolete.js").exists()
    assert (dst / "fyi/tree-sitter-version").read_text() == "tree-sitter 0.26.3\n"

    (src / "config/obsolete").unlink()
    (src / "config/current").write_text("second\n")
    manifest.write_text("toy/current.js\n")
    (langdir / "obsolete.js").unlink()
    if removed == "manifest":
        manifest.unlink()
    elif removed == "version_header":
        parser.write_text("// no version header\n")
    elif removed == "parser":
        parser.unlink()

    copy_generated(src, dst, langdir)
    assert not (dst / "config/obsolete").exists()
    assert (dst / "config/current").read_text() == "second\n"
    assert not (dst / "fyi/toy/obsolete.js").exists()
    if removed == "manifest":
        assert not (dst / "fyi").exists()
    else:
        assert (dst / "fyi/toy/current.js").read_text() == "current\n"
        assert "obsolete.js" not in (dst / "fyi/versions").read_text()
        assert (dst / "fyi/tree-sitter-version").exists() == (removed == "file")
