#! /bin/sh
#
# Fetch rules and targets prior for the "r2c" benchmark.
#
# rule_dir: input/semgrep-rules/??
# target_dir: input/r2c-ci.yml
#
# Uses sh because bash is not installed within the semgrep docker container.
#
set -eu

mkdir -p input

cp r2c-ci.yml input
cd input

# Obtain a shallow clone of a git repo for a specific commit
shallow_clone() {
  if [ -d "$name" ]; then
    echo "Reusing repo '$name'"
  else
    echo "Obtaining a shallow clone of git repo '$name', commit $commit"
    mkdir -p "$name"
    (
      cd "$name"
      git init
      git remote add origin "$url"
      git fetch --depth 1 origin "$commit"
      git checkout FETCH_HEAD -b tmp
    )
  fi
}

# Targets using other repos we run in CI
name="semgrep-app"
url="https://github.com/returntocorp/semgrep-app"
commit="45089c17aa2149dd0a893c2b8490aca8fec7f097"
shallow_clone
