#! /usr/bin/env bash
#
# Run spacegrep on the examples in examples/
# This is for quick demo purposes mostly.
#
set -eu

for pat in examples/*.pat; do
  doc=${pat%.pat}.doc
  echo "# ./bin/spacegrep -p $pat -d $doc"
  ./bin/spacegrep -p "$pat" -d "$doc"
done
