#! /usr/bin/env bash
#
# Run the statistics for all the languages instead of just one, in parallel.
# Any argument is optional and will be forwarded to the run-lang script.
#
set -eu -o pipefail

forwarded_option_list=''

usage() {
  cat <<EOF
Usage: ./run-all [OPTIONS]

Run parsing stats for all the languages supported by semgrep-core.

Options:
  --help
     Show this message and exit.
  --upload
     Upload the stats to the semgrep dashboard as soon as they're available
     for each language.
EOF
}

while [[ $# != 0 ]]; do
  case "$1" in
    --upload)
      forwarded_option_list+=" --upload"
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      error "Unsupported command-line argument: $1"
  esac
  shift
done

# Run the parsing jobs in parallel. Output may be mangled.
pid_list=''
for dir in lang/*; do
  lang=$(basename "$dir")
  ./run-lang "$lang" $forwarded_option_list &
  pid=$!
  pid_list+=" $pid"
done

for pid in $pid_list; do
  wait "$pid"
done

# Show all the results sequentially at the end
for dir in lang/*; do
  cat "$dir"/stats.json
done
