(*
   Copyright (c) 2026 Semgrep Inc.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   version 2.1 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the file
   LICENSE for more details.
*)
(**
   Git provenance of this build, captured at compile time.

   The value is generated by a dune rule; see this directory's [dune]
   for how it is derived and its fallback order.
*)

val commit : string
(** Short commit SHA the binary was built from, with a ["-dirty"] suffix
    when the build's working tree had uncommitted tracked changes, or
    ["unknown"] when no git information was available at build time. *)
