#! /usr/bin/env bash
#
# Create a version.ml file. Requires being in a git repo.
#
set -eu

version=$(git describe --always --dirty --tags --long 2>/dev/null || true)

if [[ -z "$version" ]]; then
  version="dev"
fi

cat <<EOF
(* generated at build time by $0 *)

(*
  semgrep-core version.
*)
let version = "$version"
EOF
