#! /usr/bin/env bash
#
# CI job that checks whether semgrep-proprietary can compile using the
# current semgrep commit as a submodule.
#
set -eu

semgrep_pro_url="https://github.com/returntocorp/semgrep-proprietary.git"
semgrep_root=$(git rev-parse --show-toplevel)
semgrep_commit=$(git rev-parse --short=7 HEAD)

echo <<EOF
We're attempting to build semgrep-proprietary using the current version
of semgrep. We're assuming we're in a folder within the semgrep repo.

Here's what we found about semgrep:

semgrep repo root: $semgrep_root
semgrep commit: $semgrep_commit
semgrep-proprietary remote URL: $semgrep_pro_url
semgrep git status:
$(cd "$semgrep_root" && git status)
EOF

# Use a folder where it's safe to delete any existing semgrep-proprietary.
workdir=$semgrep_root/../tmp-semgrep-pro
mkdir -p "$workdir"
(
  cd "$workdir"
  rm -rf semgrep-proprietary
  git clone "$semgrep_pro_url" --depth 1
  (
    cd semgrep-proprietary
    echo "semgrep-proprietary work folder: $(pwd)"

    # Fetch all submodules (although we don't need the semgrep submodule)
    git submodule update --init --recursive --depth 1

    # Replace the semgrep submodule
    rm -rf semgrep
    ln -s "$semgrep_root" semgrep

    # Build semgrep-proprietary
    make
  )
)
