#! /usr/bin/env bash
#
# Install tree-sitter's and ocaml-tree-sitter's runtime libraries.
#
set -eu

# We don't plug in this repo as a submodule because itself contains over
# 600 MB of submodules (tree-sitter-* repos) which are not needed
# to build semgrep-core.
#
if [[ ! -d ocaml-tree-sitter ]]; then
  git clone https://github.com/returntocorp/ocaml-tree-sitter.git
fi

cd ocaml-tree-sitter
git fetch -p origin

# The current version of ocaml-tree-sitter being used.
#
# In general, there's no need to change this when a tree-sitter parser is
# updated or created. In theory, this needs only change when the scripts
# below change or when the runtime library changes (src/run, src/bindings).
# If unsure, just update to the latest commit on the main branch.
#
git checkout 8f2515c

./scripts/install-runtime
./configure
