#! /usr/bin/env bash
#
# Install tree-sitter's runtime library and inject ocaml-tree-sitter's
# runtime code to be built with semgrep-core.
#
set -eu

cd semgrep-core/src/ocaml-tree-sitter

# Install the C library. OCaml sources are built as part of the semgrep-core
# dune project. See the symlinks in semgrep-core/src/ocaml-tree-sitter.
./scripts/install-tree-sitter-lib
