#! /usr/bin/env bash
#
# Install tree-sitter's and ocaml-tree-sitter's runtime libraries.
#
set -eu

cd ocaml-tree-sitter

# In homebrew, tree-sitter formula is used as dependency
# instead of installing manually so skip installing tree-sitter-lib
if [[ -z "${HOMEBREW_SYSTEM+x}" ]]; then
	./scripts/install-runtime
else
	opam install -y .
fi

./configure
