#!/usr/bin/env python3
"""
sync-grammar-fyi.py LANGDIR DST PARSER_C

Refreshes DST/fyi/ (docs, not a build input): which upstream grammar commit
and tree-sitter version a regenerated parser came from. Mirrors
copy_fyi_files in libs/ocaml-tree-sitter-semgrep/lang/release. Called by
regen-grammar; not meant to be run standalone.

LANGDIR/fyi.list lists paths (relative to ots's lang/ dir, LANGDIR's parent)
to copy into DST/fyi/, each with a git provenance blurb. No-op if
LANGDIR/fyi.list is absent.
"""
import subprocess
import sys
from pathlib import Path

GENERATED_BY_PREFIX = "// semgrep: generated by "
PROG = Path(sys.argv[0]).name


def git(repo_dir: Path, *args: str) -> str | None:
    """Run `git -C repo_dir <args>`; return trimmed stdout, or None + a
    stderr WARNING on failure (provenance for a docs file, not a build
    input, so it shouldn't abort regen-grammar, but shouldn't fail silently
    either)."""
    result = subprocess.run(
        ["git", "-C", str(repo_dir), *args], capture_output=True, text=True
    )
    if result.returncode != 0:
        print(
            f"{PROG}: WARNING git -C {repo_dir} {' '.join(args)} failed: "
            f"{result.stderr.strip()}",
            file=sys.stderr,
        )
        return None
    return result.stdout.strip()


def provenance_entry(path: Path, rel_path: str) -> str:
    """Build the File/Git repo name/Latest commit/Last change block for one fyi file."""
    repo_dir = path.parent
    toplevel = git(repo_dir, "rev-parse", "--show-toplevel")
    repo_name = Path(toplevel).name if toplevel is not None else None
    # Unlike repo_name/HEAD (an unknown identity), no log output legitimately
    # means "nothing to report" here, not "unknown" -- don't render it as None.
    last_change = git(repo_dir, "log", "-1", "--", path.name) or ""
    indented = "\n".join("  " + line for line in last_change.splitlines())
    return (
        f"File: {rel_path}\n"
        f"Git repo name: {repo_name}\n"
        f"Latest commit in repo: {git(repo_dir, 'rev-parse', 'HEAD')}\n"
        "Last change in file:\n"
        f"{indented}\n---\n"
    )


def write_tree_sitter_version(parser_c: Path, fyi_dst: Path) -> None:
    """Copy parser.c's "generated by" comment into fyi_dst/tree-sitter-version."""
    if not parser_c.exists():
        return
    for line in parser_c.read_text(errors="replace").splitlines():
        if line.startswith(GENERATED_BY_PREFIX):
            (fyi_dst / "tree-sitter-version").write_text(
                line[len(GENERATED_BY_PREFIX) :] + "\n"
            )
            return


def copy_fyi_files(
    fyi_list: Path, ots_lang_dir: Path, fyi_dst: Path
) -> list[str] | None:
    """Copy each file listed in fyi_list into fyi_dst; return their
    provenance entries, or None (+ stderr error) if a listed file is missing."""
    entries = []
    for rel_path in fyi_list.read_text().splitlines():
        rel_path = rel_path.strip()
        if not rel_path or rel_path.startswith("#"):
            continue
        path = ots_lang_dir / rel_path
        if not path.exists():
            print(f"{PROG}: missing fyi file '{rel_path}'", file=sys.stderr)
            return None
        dstf = fyi_dst / rel_path
        dstf.parent.mkdir(parents=True, exist_ok=True)
        dstf.write_bytes(path.read_bytes())
        entries.append(provenance_entry(path, rel_path))
    return entries


def main() -> int:
    """Parse argv and refresh LANGDIR's fyi/ output; no-op if there's no fyi.list."""
    if len(sys.argv) != 4:
        print(f"usage: {PROG} LANGDIR DST PARSER_C", file=sys.stderr)
        return 2
    langdir, dst, parser_c = (Path(a) for a in sys.argv[1:])

    fyi_list = langdir / "fyi.list"
    if not fyi_list.exists():
        return 0

    fyi_dst = dst / "fyi"
    fyi_dst.mkdir(parents=True, exist_ok=True)

    entries = copy_fyi_files(fyi_list, langdir.parent, fyi_dst)
    if entries is None:
        return 1

    write_tree_sitter_version(parser_c, fyi_dst)
    (fyi_dst / "versions").write_text("".join(entries))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
