##############################################################################
# Variables
##############################################################################
-include ../Makefile.config

SRC=objet.ml \
 ocollection.ml\
 seti.ml setPt.ml \
 oset.ml oassoc.ml osequence.ml oarray.ml  \
 osetb.ml oseth.ml oseti.ml \
 oassocb.ml oassoch.ml \
 ograph.ml ograph_extended.ml ograph_simple.ml  ograph2way.ml \
 oassoc_buffer.ml \
 ofullcommon.ml

INCLUDEDIRS=../commons

LIBNAME=lib
OPAMPKG=commons_ocollection

OCAMLMKLIB=ocamlc -a
OCAMLMKLIBOPT=ocamlopt -a

-include ../commons/Makefile.common
