(*
   Copyright (c) 2021-2024 Semgrep Inc.

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public License
   version 2.1 as published by the Free Software Foundation.

   This library is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the file
   LICENSE for more details.
*)
(* The test suite is generated by scanning the file system *)

val tests : unit -> Testo.t list

type error_tolerance =
  | Strict
  (* expect "missing tokens" inserted by the tree-sitter parser *)
  | Missing_tokens
  (* expect error nodes created by the tree-sitter parser *)
  | Partial_parsing
  (* expect some error, test status will be XFAIL *)
  | Todo

(* For semgrep-proprietary: make a test suite for a specific list of
   languages.
*)
val make_tests : (Lang.t * error_tolerance) list -> Testo.t list
