#! /usr/bin/env bash
#
# Run the semgrep-core test program from the correct folder.
# This is meant for manual use, when we want to select which tests to run.
#

cd _build/default/tests
./test.exe "$@"
