from typing import Any, List, Type

def get_all(type_obj: Type[bool], include_subtypes: bool = ...) -> List[Any]: ...

class GCToggler:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: None, exc_val: None, exc_tb: None) -> None: ...
