repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/returntocorp/pre-commit-ocaml
    rev: v1.0.0
    hooks:
      - id: ocp-indent
