name: semgrep
on:
  workflow_dispatch:
  pull_request:

jobs:
  semgrep-run-r2c-config:
    name: semgrep with r2c registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@stable
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: "1"
