# This workflow builds and test semgrep-core. It also generates an
# ocaml-build-artifacts.tgz file which is used in many other jobs such
# as test-cli in tests.yml or build-wheels-manylinux in
# build-test-manylinux-x86.yaml

name: build-test-core-x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-test-core-x86:
    name: Build Test Semgrep Core
    runs-on: ubuntu-latest
    # This container has opam already installed, as well as an opam switch 4.14.0
    # already created, and a big set of packages already installed. Thus,
    # the 'make install-deps-ALPINE-for-semgrep-core' below is very fast and
    # almost a noop.
    container: returntocorp/ocaml:alpine-2023-06-16
    # We need this hack because GHA tampers with the HOME in container
    # and this does not play well with 'opam' installed in /root
    env:
      HOME: /root
    steps:
      - name: Make checkout speedy
        run: git config --global fetch.parallel 50
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build semgrep-core
        run: |
          eval $(opam env)
          make install-deps-ALPINE-for-semgrep-core
          make install-deps-for-semgrep-core
          make core
          mkdir -p ocaml-build-artifacts/bin
          cp bin/semgrep-core ocaml-build-artifacts/bin/
          tar czf ocaml-build-artifacts.tgz ocaml-build-artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: ocaml-build-artifacts.tgz
          name: ocaml-build-artifacts-release
      - name: Test semgrep-core
        run: opam exec -- make core-test
