name: build-core-arm-mac
"on":
  workflow_dispatch:
    inputs:
      use-cache:
        description: Use Opam Cache - uncheck the box to disable use of the opam cache,
          meaning a long-running but completely from-scratch build.
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      use-cache:
        description: Use Opam Cache - uncheck the box to disable use of the opam cache,
          meaning a long-running but completely from-scratch build.
        required: false
        type: boolean
        default: true
jobs:
  build-core:
    runs-on: macos-13-xlarge
    env:
      OPAM_SWITCH_NAME: 4.14.0
    steps:
    - name: Setup runner directory
      run: "\n    sudo mkdir /Users/runner\n    sudo chown admin:staff /Users/runner\n
        \   sudo chmod 750 /Users/runner\n  "
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Cache Opam
      uses: actions/cache@v3
      if: ${{ inputs.use-cache }}
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      with:
        path: ~/.opam
        key: ${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME }}-opam-deps-${{
          github.run_id }}
        restore-keys: ${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME
          }}-opam-deps\n
    - name: Install dependencies
      run: ./scripts/osx-setup-for-release.sh "${{ env.OPAM_SWITCH_NAME }}"
    - name: Compile semgrep
      run: "\n        opam exec -- make core\n        mkdir -p artifacts\n        cp
        ./bin/semgrep-core artifacts\n        zip -r artifacts.zip artifacts\n      "
    - uses: actions/upload-artifact@v3
      with:
        path: artifacts.zip
        name: semgrep-osx-arm64-${{ github.sha }}