name: build-test-manylinux-x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu-16-04:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:ubuntu-16.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: ocaml-build-artifacts-release
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts.tgz
          mkdir -p semgrep-files
          cp ocaml-build-artifacts/bin/* semgrep-files
      - run: ./scripts/ubuntu-release.sh
      - uses: actions/upload-artifact@v3
        with:
          name: semgrep-ubuntu-16.04-${{ github.sha }}
          path: artifacts.tar.gz
