# This workflow depends on build-test-core-x86.yaml to generate
# the appropriate ocaml-build-artifacts.tgz file
#TODO: What is this workflow used for? we dont release anymore
# those semgrep-xxx version assets, so do we still need this workflow?

name: build-test-ubuntu-16-04-x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-ubuntu-16-04:
    runs-on: ubuntu-latest
    #TODO? what is this container? sgrep?
    container: returntocorp/sgrep-build:ubuntu-16.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: ocaml-build-artifacts-release
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts.tgz
          mkdir -p semgrep-files
          cp ocaml-build-artifacts/bin/* semgrep-files
      - run: |
          # Make a semgrep release for Linux x86_64.
          # We may not need all of these packages anymore since semgrep-core now
          # comes pre-built.
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libexpat1-dev gettext libz-dev libssl-dev build-essential autoconf musl-tools
          chmod +x semgrep-files/semgrep-core
          tar -cvzf artifacts.tar.gz semgrep-files/
      - uses: actions/upload-artifact@v3
        with:
          path: artifacts.tar.gz
          name: semgrep-ubuntu-16.04-${{ github.sha }}
