name: build-test-manylinux-x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-test-ubuntu-x86:
    uses: ./.github/workflows/build-manylinux-x86.yaml
    secrets: inherit

  build-ubuntu-16-04:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:ubuntu-16.04
    needs: [build-test-ubuntu-x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts.tgz
          mkdir -p semgrep-files
          cp ocaml-build-artifacts/bin/* semgrep-files
      - name: Run Ubuntu build script
        run: ./scripts/ubuntu-release.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-ubuntu-16.04-${{ github.sha }}
          path: artifacts.tar.gz

  test-binary-ubuntu:
    runs-on: ubuntu-22.04
    needs: [build-ubuntu-16-04]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: semgrep-ubuntu-16.04-${{ github.sha }}
      - name: untar artifacts
        run: tar xzvf artifacts.tar.gz
      - name: test package
        run: ./semgrep-files/semgrep-core -version
