# This workflow builds and tests the semgrep-core binary for macOS x86
# but does so on the github-hosted macos-12 runner. This'll run as a background job for the time being
# once we build confidence, we'll swap over the regular build-test-osx-x86.yaml to use this runner,
# and remove this file.

# coupling: if you modify this file, modify also build-test-osx-m1.yaml
name: build-test-osx-x86

on:
  workflow_dispatch: {}
  schedule:
    - cron: "37 16 * * *"
    - cron: "37 12 * * *"
    - cron: "37 08 * * *"

jobs:
  build-core-osx:
    name: Build the OSX binaries
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          ./scripts/osx-setup-for-release.sh
          opam exec -- make core
          mkdir -p artifacts
          cp ./bin/semgrep-core artifacts
          zip -r artifacts.zip artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: artifacts.zip
          name: semgrep-osx-${{ github.sha }}

  build-wheels-osx:
    runs-on: macos-12
    needs: [build-core-osx]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          name: semgrep-osx-${{ github.sha }}
      - run: unzip artifacts.zip
      - env:
          # Relative because build-wheels does a 'cd cli'
          SEMGREP_CORE_BIN: ../artifacts/semgrep-core
        run: ./scripts/build-wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          path: cli/dist.zip
          name: osx-wheel

  test-wheels-osx:
    runs-on: macos-12
    needs: [build-wheels-osx]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: osx-wheel
      - run: unzip ./osx-wheel/dist.zip
      - name: install package
        run: pip3 install dist/*.whl
      - run: semgrep --version
      - name: e2e semgrep-core test
        run: echo '1 == 1' | semgrep --debug -l python -e '$X == $X' -
      - name: test dynamically linked libraries are in /usr/lib/
        shell: bash {0}
        run: |
          otool -L $(semgrep --dump-engine-path) > otool.txt
          if [ $? -ne 0 ]; then
            echo "Failed to list dynamically linked libraries.";
            cat otool.txt;
            exit 1;
          fi
          NON_USR_LIB_DYNAMIC_LIBRARIES=$(cat otool.txt | tail -n +2 | grep -v "^\s*/usr/lib/")
          if [ $? -eq 0 ]; then
            echo "Error: semgrep-core has been dynamically linked against libraries outside /usr/lib:"
            echo $NON_USR_LIB_DYNAMIC_LIBRARIES
            exit 1;
          fi;
