# Verify Homebrew Core Formula Works
name: homebrew-core-head

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

jobs:
  mac-build:
    name: Check brew install formula works for develop head
    runs-on: macos-latest
    steps:
      - name: Brew update
        run: brew update
      - name: Brew Install
        run: brew install semgrep --HEAD
      - name: Check installed correctly
        run: brew test semgrep --HEAD
