# This workflow is a subset of as the nightly.yml,
# but runs on the github-hosted macos-12 runner. This'll run as a background job for the time being
# once we build confidence, we'll swap over the regular build-test-osx-x86.yaml to use this runner,
# and remove this file.

name: Nightly Verification

on:
  workflow_dispatch:
  schedule:
    - cron: "37 15 * * *"
    - cron: "37 11 * * *"
    - cron: "37 07 * * *"

jobs:
  brew-build:
    name: Build Semgrep via Brew from `returntocorp/semgrep:develop`
    runs-on: macos-12
    # We've had issues with this workflow in the past, and needed to ensure that homebrew wouldn't use the API.
    # See: https://github.com/orgs/Homebrew/discussions/4150, https://github.com/orgs/Homebrew/discussions/4136
    # There's also much other discussion on this topic available on GH and in the brew discussions.
    steps:
      - name: Brew update
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1
        run: brew update --debug --verbose
      - name: Brew Install
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1
        run: brew install semgrep --HEAD --debug
      - name: Check installed correctly
        env:
          HOMEBREW_NO_INSTALL_FROM_API: 1
        run: brew test semgrep --HEAD
