# Workflow to manually promote the returntocorp/semgrep:canary docker image
# to returntocorp/semgrep:latest that most customers are using

name: Promote returntocorp/semgrep:canary to :latest

on:
  workflow_dispatch:
    inputs:
      confirmed:
        description: "Are you sure you want to do this? This is a sensitive operation"
        type: boolean
        required: true
        default: false

jobs:
  promote:
    name: promote :canary to :latest
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - env:
          confirmed: ${{ inputs.confirmed }}
        run: |
          canary_digest=$(docker buildx imagetools inspect --raw returntocorp/semgrep:canary | jq -r .config.digest)
          latest_digest=$(docker buildx imagetools inspect --raw returntocorp/semgrep:latest | jq -r .config.digest)
          if [[ "${confirmed}" == "true" ]]; then
            echo "Promoting returntocorp/semgrep:canary (${canary_digest}) to returntocorp/semgrep:latest (was ${latest_digest})"
            docker buildx imagetools create -t returntocorp/semgrep:latest returntocorp/semgrep:canary
          else
            echo "Would have promoted returntocorp/semgrep:canary (${canary_digest}) to returntocorp/semgrep:latest (was ${latest_digest})"
          fi
