name: publish-javascript

on:
  workflow_dispatch:

jobs:
  publish-javascript:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::338683922796:role/returntocorp-semgrep-deploy-role
          role-duration-seconds: 900
          role-session-name: "semgrep-s3-access"
          aws-region: us-west-2
      - uses: actions/download-artifact@v3
        with:
          name: semgrep-js-artifacts-${{ github.sha }}
          path: /tmp/semgrep
      - name: Upload to S3
        run: |
          tar xvzf /tmp/semgrep/semgrep-js-artifacts.tar.gz
          aws s3 sync --dryrun /tmp/semgrep/js/ "s3://semgrep-app-static-assets/static/turbo/sha-${{ github.sha }}/"
