name: PR

on:
  pull_request:
    types: [opened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-checklist
          only_create: true
          message: |
            PR checklist:

            - [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
            - [ ] Tests included or PR comment includes a reproducible test plan
            - [ ] Documentation is up-to-date
            - [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
            - [ ] Change has no security implications (otherwise, ping security team)

            If you're unsure about any of this, please see:

            - [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
            - [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)
