# Workflow to manually revert the semgrep 'canary' docker image
# to a previous version.
#TODO: should factorize with revert-semgrep-latest-docker-image.yml

name: Revert Semgrep Canary Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag to point 'canary' to, example: 1.40.0"
        required: true

jobs:
  rollback-docker-image:
    name: Rollback returntocorp/semgrep Docker Image
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE_REPO: returntocorp/semgrep
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: pull
        name: Pull Image to Retag as Canary
        run: |
          docker pull ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }}
      - id: retag
        name: Re-Tag Docker Image
        run: |
          docker tag ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }} ${{ env.DOCKER_IMAGE_REPO }}:canary
      - id: push
        name: Push New Latest Tag
        run: |
          docker push ${{ env.DOCKER_IMAGE_REPO }}:canary
