# Workflow to manually set the returntocorp/semgrep:canary docker image
# to a specific version (usually to point to a past version in case of rollback)
#TODO: should factorize with revert-semgrep-latest-docker-image.yml

name: Set returntocorp/semgrep:canary

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to point 'canary' to, example: 1.40.0"
        required: true

jobs:
  set-docker-image:
    name: Set the returntocorp/semgrep:canary docker image
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE_REPO: returntocorp/semgrep
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker pull ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }}
          docker tag ${{ env.DOCKER_IMAGE_REPO }}:${{ inputs.docker_tag }} ${{ env.DOCKER_IMAGE_REPO }}:canary
          docker push ${{ env.DOCKER_IMAGE_REPO }}:canary
