# Workflow to manually point a returntocorp/semgrep docker image tag
# to a specific digest (usually to point to a past version in case of rollback)

# To make a comparison to git:
# - docker image == git repository
#   example: returntocorp/semgrep
#
# - docker tag == git ref
#   example: :latest
#
# - docker digest == git commit
#   example: sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4

name: Set returntocorp/semgrep docker tag

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Semgrep docker image to update"
        type: choice
        required: true
        options:
          - returntocorp/semgrep-test # testing image, we will eventually remove the option and hardcode to returntocorp/semgrep
          - returntocorp/semgrep
          - semgrep/semgrep
      docker_tag:
        description: "Docker tag to update"
        type: choice
        required: true
        options:
          - canary
          - canary-nonroot
          - latest
          - latest-nonroot
      image_ref:
        description: "Docker tag or digest of returntocorp/semgrep to point to, example: 1.40.0 or sha256:xxx"
        type: string
        required: true
      debug:
        description: "Check to enable verbose logging of bash commands"
        type: boolean
        required: true
        default: false
      confirmed:
        description: "Are you sure you want to do this? This is a sensitive operation"
        type: boolean
        required: true
        default: false

jobs:
  set-docker-image-tag:
    name: Set the ${{ inputs.docker_image }}:${{ inputs.docker_tag }} docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: set-docker-image-tag
        env:
          docker_image: ${{ inputs.docker_image }}
          docker_tag: ${{ inputs.docker_tag }}
          image_ref: ${{ inputs.image_ref }}
          confirmed: ${{ inputs.confirmed }}
          debug: ${{ inputs.debug }}
        run: |
          if [[ "${debug}" == "true" ]]; then
            echo "Enabling debug logging..."
            set -x
          fi

          source_image="returntocorp/semgrep:${image_ref}"
          target_image="${docker_image}:${docker_tag}"

          old_digest=$(docker buildx imagetools inspect --format '{{printf "%s" .Manifest.Digest}}' ${target_image} || echo "(not found)")
          new_digest=$(docker buildx imagetools inspect --format '{{printf "%s" .Manifest.Digest}}' ${source_image} || echo "")

          echo ""

          if [[ "${new_digest}" == "" ]]; then
            echo "Error: ${source_image} did not resolve to a manifest list"
            echo "If this is urgent, you can manually login to our Docker Hub account and then run these commands to point to an arch-specific image:"
            echo "docker pull ${source_image}"
            echo "docker tag ${source_image} ${target_image}"
            echo "docker push ${target_image}"
            exit 1
          fi

          echo "Resolved ${source_image} to digest: ${new_digest}"
          echo ""

          echo "Will update ${target_image} from ${old_digest} to ${new_digest}"
          echo ""
          if [[ "${confirmed}" == "true" ]]; then
            docker buildx imagetools create -t ${target_image} ${source_image}
          else
            echo "(dry run)"
            docker buildx imagetools create --dry-run -t ${target_image} ${source_image}
            echo "(dry run)"
          fi
