# Workflow to manually set the returntocorp/semgrep:canary docker image
# to a specific version (usually to point to a past version in case of rollback)
#TODO: should factorize with revert-semgrep-latest-docker-image.yml

name: Set semgrep docker tag

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Semgrep docker image to update"
        type: choice
        required: true
        options:
          - returntocorp/semgrep-dev
          - returntocorp/semgrep
      docker_tag:
        description: "Semgrep docker image tag to update"
        type: choice
        required: true
        options:
          - canary
          - latest
      image_ref:
        description: "Docker ref to point to, example: 1.40.0"
        type: string
        required: true
      confirmed:
        description: "Are you sure you want to do this? This is a sensitive operation"
        type: boolean
        required: true
        default: false

jobs:
  set-docker-image-tag:
    name: Set the ${{ inputs.docker_image }}:${{ inputs.docker_tag }} docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - env:
          docker_image: ${{ inputs.docker_image }}
          docker_tag: ${{ inputs.docker_tag }}
          image_ref: ${{ inputs.image_ref }}
        run: |
          source_image="${docker_image}:${image_ref}"
          target_image="${docker_image}:${docker_tag}"

          old_digest=$(docker buildx imagetools inspect ${target_image})
          new_digest=$(docker buildx imagetools inspect ${source_image})

          if [[ -z "${new_digest}" ]]; then
            echo "Error: ${source_image} did not resolve to a manifest list"
            exit 1
          fi

          echo "Will update ${target_image} from ${old_digest} to ${new_digest}"
          if [[ "${confirmed}" == "true" ]]; then
            docker buildx imagetools create -t ${target_image} ${source_image}
          else
            echo "(dry run, nothing changed)"
          fi
