name: test-semgrep-pro

on:
  workflow_dispatch:
    inputs:
      artifact-name:
        required: true
        type: string
        description: Name (key) to use when uploading the docker image tarball as a artifact
      repository-name:
        required: true
        type: string
        description: The repository/name of the docker image to push, e.g., returntocorp/semgrep
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        description: Name (key) to use when uploading the docker image tarball as a artifact
      repository-name:
        required: true
        type: string
        description: The repository/name of the docker image to push, e.g., returntocorp/semgrep

jobs:
  setup-docker-tag:
    name: Set up Docker tag based on if this is a pull request
    runs-on: ubuntu-22.04
    outputs:
      docker-tag: ${{ steps.setup-docker-tag.outputs.docker-tag }}
    steps:
      - name: Setup Docker Tag
        id: setup-docker-tag
        run: |
          echo "Github event is ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "docker-tag=pr-${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
            echo "Setting docker tag to current pull request number"
          else
            echo "docker-tag=develop" >> "$GITHUB_OUTPUT"
            echo "Setting dry-run to develop"
          fi
  test-semgrep-pro:
    name: Test Semgrep Pro Engine
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    needs: setup-docker-tag
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}-arch-amd64
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::338683922796:role/returntocorp-semgrep-deploy-role
          role-duration-seconds: 900
          role-session-name: "semgrep-deploy"
          aws-region: us-west-2
      # This is the `develop` binary, so this is truly the most recent version of
      # `semgrep-proprietary` from that repository's `develop` branch.
      # We test with this so that we know whether any changes we make on this PR are breaking with
      # the `develop` branch of `pro`.
      - name: Download Semgrep Pro `develop` binary
        run: |
          aws s3 cp s3://web-assets.r2c.dev/assets/semgrep-core-proprietary-manylinux-develop ./semgrep-core-proprietary
      - name: Run Semgrep Pro Engine!
        run: |
          docker run --rm -v "$(pwd):/root" -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} --entrypoint=bash "${{ inputs.repository-name }}:${{ needs.setup-docker-tag.outputs.docker-tag }}" /root/scripts/test-pro.sh
