# Validate a Release
name: validate-release-test

on:
  workflow_dispatch:
  push:
    branches:
      - spencer/pa-1229-homebrew-release-script-failing

jobs:
  homebrew-core-pr-test:
    name: Update on Homebrew-Core
    runs-on: macos-10.15
    strategy:
      matrix:
        python: ["3.9.12"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          # Needs to be < 3.10 see https://github.com/returntocorp/semgrep/issues/4213
          python-version: ${{ matrix.python }}
      - name: Brew update
        run: brew update
      - name: Install brew pipgrip
        run: brew install pipgrip
      - name: Install pip pipgrip
        run: pip install pipgrip
      - name: Point homebrew pipgrip to pip pipgrip
        # Homebrew brew calls brew pipgrip internally but brew pipgrip is pinned to python3.10
        # this tricks it into using our 3.9 pipgrip
        run: rm /usr/local/opt/pipgrip/bin/pipgrip && ln /Users/runner/hostedtoolcache/Python/${{ matrix.python }}/x64/bin/pipgrip /usr/local/opt/pipgrip/bin/pipgrip
      # - uses: dawidd6/action-homebrew-bump-formula@v3
      #   with:
      #     token: ${{ secrets.HOMEBREW_PR_TOKEN }}
      #     formula: semgrep
      #     org: returntocorp
      #     force: true