name: test-build-outputs

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

jobs:
  build-test-docker:
    uses: ./.github/workflows/build-test-docker.yaml
    secrets: inherit

  build-test-manylinux-x86:
    uses: ./.github/workflows/build-test-manylinux-x86.yaml
    secrets: inherit

  build-test-osx-x86:
    uses: ./.github/workflows/build-test-osx-x86.yaml
    secrets: inherit

  build-test-osx-m1:
    uses: ./.github/workflows/build-test-osx-m1.yaml
    secrets: inherit
