# Name of this GitHub Actions workflow.
name: Trigger Doc Update

# Only trigger when the release workflow has succeeded
on:
  workflow_run:
    workflows: ["release"]
    types: [completed]

jobs:
  trigger-doc-update:
    name: Trigger Doc Update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger doc update workflow
        run: |
            curl --location \
            --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{ secrets.DISPATCH_SECRET }}" \
            https://api.github.com/repos/returntocorp/semgrep-docs/dispatches \
            --data '{"event_type":"new_release"}'
